# Generated by Django 2.2.8 on 2020-02-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_auto_20200207_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='publication',
            name='moderation',
        ),
        migrations.AddField(
            model_name='publication',
            name='moderation_status',
            field=models.IntegerField(choices=[(0, 'published'), (1, 'draft'), (2, 'pre-moderation'), (3, 'rejected')], default=1),
        ),
    ]
