# Generated by Django 2.2.8 on 2020-02-08 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_auto_20200208_0942'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
