# Generated by Django 2.2.8 on 2020-02-08 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='publications.Publication'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='moderation_status',
            field=models.IntegerField(choices=[(0, 'approved'), (1, 'draft'), (2, 'pre-moderation'), (3, 'declined')], default=1),
        ),
    ]
