# Generated by Django 2.2.8 on 2020-02-09 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_auto_20200209_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-date_pub']},
        ),
    ]
