# Generated by Django 2.2.8 on 2020-02-09 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('socialaccount', '0003_extra_data_default_dict'),
        ('account', '0002_email_max_length'),
        ('publications', '0010_auto_20200209_1743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
