# Generated by Django 2.2.8 on 2020-02-09 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0011_delete_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicationPhoto',
        ),
    ]
